loadbalancer/src/main/java/com/assoc/jad/loadbalancer/bean/HealthCheckBean.java
package com.assoc.jad.loadbalancer.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpServletRequest;

import com.assoc.jad.loadbalancer.tools.LoadBalancerStatic;

@ManagedBean
@SessionScoped
public class HealthCheckBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private String infomsg;
	private String selectedApp;
	private String applications;
	private List<SelectItem> applicationList  = new ArrayList<SelectItem>();
	private String resetBeanValues;

	private Object instanceKey;

	private void bldApplicationList() {
		if (applicationList.size() > 0) return;
		
		StringBuilder sb = new StringBuilder();
		Iterator<?> iter = LoadBalancerStatic.applications.keySet().iterator();
		while (iter.hasNext()) {
			String key = (String) iter.next();
			SelectItem item = new SelectItem();
			item.setLabel(key);
			item.setValue(key);
			applicationList.add(item);
			sb.append(key).append(' ');
		}
		selectedApp = (String) applicationList.get(0).getValue();
		applications = sb.toString();
	}
	private String getHTMLParam(String name) {
		FacesContext context = FacesContext.getCurrentInstance();
		ExternalContext external = context.getExternalContext();
		HttpServletRequest request = (HttpServletRequest) external.getRequest();
		return request.getParameter(name);
	}

	public Set<String> getApplicationService() {
		if (LoadBalancerStatic.applications.get(selectedApp) == null) return null;
		
		return LoadBalancerStatic.applications.get(selectedApp).keySet();
	}
	public Collection<HashMap<String, String>> getService() {
		Collection<HashMap<String, String>> serviceParms = LoadBalancerStatic.applications.get(selectedApp).values();
		return serviceParms;
	}
	public HashMap<String,HashMap<String,String>> getService2() {
		HashMap<String,HashMap<String,String>> serviceParms = LoadBalancerStatic.applications.get(selectedApp);
		return serviceParms;
	}
	
	public HashMap<String, HashMap<String, HashMap<String, List<String>>>> getPerformanceService() {
		if (selectedApp == null) bldApplicationList();		
		return LoadBalancerStatic.allServicesData.get(selectedApp);
	}
	public HashMap<String,HashMap<String,List<String>>> getInstanceData() {
		if (instanceKey == null) getResetBeanValues();
		HashMap<String,HashMap<String,HashMap<String,List<String>>>> appInstances = LoadBalancerStatic.allServicesData.get(selectedApp);
		if (appInstances == null) return null;
		
		HashMap<String,HashMap<String,List<String>>> instance = appInstances.get(instanceKey);
		return instance;
	}	
	public String getInfomsg() {
		return infomsg;
	}
	public void setInfomsg(String infomsg) {
		this.infomsg = infomsg;
	}
	public String getSelectedApp() {
		//if (this.selectedApp == null) this.selectedApp = LoadBalancerStatic.applications.keySet().iterator().next();
		return selectedApp;
	}
	public void setSelectedApp(String selectedApp) {
		this.selectedApp = selectedApp;
	}
	public List<SelectItem> getApplicationList() {
		bldApplicationList();
		return applicationList;
	}
	public void setApplicationList(List<SelectItem> applicationList) {
		this.applicationList = applicationList;
	}
	public String getApplications() {
		bldApplicationList();
		return applications;
	}
	public void setApplications(String applications) {
		this.applications = applications;
	}
	public String getResetBeanValues() {
		this.selectedApp = this.getHTMLParam("application");
		this.instanceKey = this.getHTMLParam("instancekey");
		return this.resetBeanValues;
	}
	public void setResetBeanValues(String resetBeanValues) {
		this.resetBeanValues = resetBeanValues;
	}
}

loadbalancer/src/main/java/com/assoc/jad/loadbalancer/BalancerServlet.java
package com.assoc.jad.loadbalancer;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.List;

import javax.servlet.Servlet;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.assoc.jad.loadbalancer.tools.LoadBalancerStatic;

public class BalancerServlet extends HttpServlet implements Servlet {

	private static final long serialVersionUID = 1L;

	public static String configRoot;
	private static String host = "localhost";
	private static int port = 80;
	private static int counter = 0;
	private static String balancer;
	private static String subdir;
	private enum loadBalancerVars {
		loadBalancerURL(String.format("\tloadBalancerURL: \"http://%s:%d%s%s\",", host,port,balancer,subdir)),  //javascript var spacename syntax.
		loadBalancerCounter(String.format("windowNamw = %s;", counter)), 
		;
		String cmd = null;
		loadBalancerVars(String cmd) {
			this.cmd = cmd;
		}
		public String getCmd() { return this.cmd;}
	}


	private void bldConfig(String filename) {
		BufferedReader inpf = null;
		
		try {
			inpf = new BufferedReader(new InputStreamReader(getClass().getResourceAsStream("/" + filename)));
			LoadBalancerStatic.applications = inpf.lines().parallel()
				.filter(str -> (!str.startsWith("#") && str.length() > 0)) 
			    .map(a -> a.trim().split("="))
			    .collect(MapsCollector::new,
			    		MapsCollector::accumulate,
			    		MapsCollector::combine
			    		)
			    .getResult();
		}finally {
			try {if (inpf != null) inpf.close();} catch (IOException e) {}
		}
	}

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		performTask(request, response);
	}

	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		performTask(request, response);
	}

	public void init() throws ServletException {
		ServletConfig config = getServletConfig();
		String configFile = config.getInitParameter("configFile");
		configRoot = config.getInitParameter("root");
		bldConfig(configFile);
		ThreadGroup loadBalancerThreads = new ThreadGroup(LoadBalancerStatic.THREADGROUP);
		new Thread(loadBalancerThreads,new InstancesHealthCheck(),"BalancerServlet").start();

	}
	@SuppressWarnings("unused")
	public void destroy() {
		Thread[] threads = new Thread[100];
		Thread.enumerate(threads);
		if (threads == null) return;
		for (Thread thread : threads) {
			if (thread.getName().equals("BalancerServlet")) {
				thread.interrupt();
				return;
			}
		}
	}
	public void run() throws IOException {
	}
	/**
	 * networkbgnTime is in the same entry in list as networkEndTime.
	 * @param request
	 */
	public void updateInstanceData(HttpServletRequest request) {
    	String application = request.getParameter("application");
    	if  (application == null) return;
    	
    	String key = request.getParameter("key");
    	String networkBgnTime = request.getParameter("networkBgnTime");
    	String networkEndTime = request.getParameter("networkEndTime");
		HashMap<String,HashMap<String,HashMap<String,List<String>>>> instances = LoadBalancerStatic.allServicesData.get(application);
		HashMap<String,HashMap<String,List<String>>> instance = instances.get(key);
		HashMap<String,List<String>> scriptParms = instance.get(request.getParameter("script"));
		if (scriptParms == null) return;
		List<String> networkBgnTimes = scriptParms.get("networkBgnTime");
		List<String> networkEndTimes = scriptParms.get("networkEndTime");
		for (int i=0;i<networkBgnTimes.size();i++) {
			if (!networkBgnTime.equals(networkBgnTimes.get(i))) continue;
			networkEndTimes.set(i, networkEndTime);
			break;
		}
		
	}
	public void updateapplication(HttpServletRequest request) {
    	String application = request.getParameter("application");
    	if (application == null) return;
    	
    	String key = request.getParameter("key");
		HashMap<String,HashMap<String,String>> appServices = LoadBalancerStatic.applications.get(application);
		HashMap<String,String> parms = appServices.get(key);
		Integer CTR = new Integer(parms.get("ctr"));
		CTR--;
		parms.put("ctr", CTR.toString());
	}
	private void requestFromService(HttpServletRequest request,HttpServletResponse response, String appCmd ) {
		
		switch (appCmd.toLowerCase()) {
        case "taskdone":
        	updateapplication(request);
        	updateInstanceData(request);
            break;
        default:
        	processFile(request,response);
        	break;
		}
	}
	private void processFile(HttpServletRequest request, HttpServletResponse response) {

		BufferedReader inpf = null;
		
		StringBuilder sb = new StringBuilder();
		sb.append(System.getProperty("catalina.base")).append(File.separator).append("webapps"); 
		String contextPath = request.getContextPath().substring(1);
		String[] URLElements = request.getRequestURL().toString().split("/");
		for (int i=0;i<URLElements.length;i++) {
			if (!contextPath.equals(URLElements[i])) continue;
			subdir = "/"+URLElements[i+1];
			for (;i<URLElements.length;i++)
				sb.append("/").append(URLElements[i]);
		}
		String type = "text/html";
		if (URLElements[URLElements.length-1].endsWith("js")) type = "text/javascript";
		
		response.setContentType(type); 
		String filePath = sb.toString();
		if (filePath.indexOf("loadbalancer") != -1 && filePath.indexOf("lbcommands") != -1) {
			setJavscriptVars(request);
			editRequest(filePath,response);
			return;
		}
		try {

	        PrintWriter out = response.getWriter();  
			inpf = new BufferedReader(new InputStreamReader(new FileInputStream(new File(filePath))));
			inpf.lines().parallel()
			    .forEach(a-> out.write(a+System.lineSeparator()));
		} catch (Exception e) {
			e.printStackTrace();
		}finally {
			try {if (inpf != null) inpf.close();} catch (IOException e) {}
		}
	}

	private void editRequest(String filePath,HttpServletResponse response ) {
		BufferedReader inpf = null;

		try {

	        PrintWriter out = response.getWriter();  
			inpf = new BufferedReader(new InputStreamReader(new FileInputStream(new File(filePath))));
			inpf.lines().parallel()
				.map(a -> {
					String[] array = a.trim().split("\\s+");
					if (array[0].equals(LoadBalancerStatic.LOADBALANCERURL)) {
						for (loadBalancerVars parm : loadBalancerVars.values()) {
							if (array[0].indexOf(parm.name()) != -1) {
								return parm.getCmd();
							}
						}
					}
					return a;
				})
			    .forEach(a-> out.write(a+System.lineSeparator()));
		} catch (Exception e) {
			e.printStackTrace();
		}finally {
			try {if (inpf != null) inpf.close();} catch (IOException e) {}
		}
	}
	private void setJavscriptVars(HttpServletRequest request) {
		host = request.getServerName();
		port = request.getServerPort();
		balancer = request.getContextPath();
		
	}

	private void performTask(HttpServletRequest request,HttpServletResponse response) throws ServletException, IOException {
		String application=request.getPathInfo().substring(1);
		HashMap<String,HashMap<String,String>> appServices = LoadBalancerStatic.applications.get(application);
		if (appServices == null) {
			requestFromService(request,response,application);	//TODO process data from service
			return;
		}
		setJavscriptVars(request);		
		String service = selectAppService(appServices);
		String url = service+"?application="+application+"&loadBalancerWSURL="+String.format("ws://%s:%d%s/websocketserver", host,port,balancer); 
		if (service == null) {	//no active service found for a given application
			response.sendRedirect("../test.xhtml");
		} else
			response.sendRedirect(url);
	}
	private String selectAppService(HashMap<String, HashMap<String, String>> appServices) {
		String savedURL = null;
		Boolean instanceAlive = false;
		for (String key1 : appServices.keySet()) {
			HashMap<String,String> instance = appServices.get(key1);
			if (!"true".equalsIgnoreCase(instance.get(LoadBalancerStatic.INSTANCEUP))) continue;
			instanceAlive = true;
			Integer CTR1 = new Integer(instance.get("ctr"));
			if (savedURL == null) savedURL = key1;
			HashMap<String,String> savedInstance = appServices.get(savedURL);
			Integer CTR2 = new Integer(savedInstance.get("ctr"));
			if (CTR2>CTR1) savedURL = key1;
		}
		if (!instanceAlive) return null;
		
		HashMap<String,String> parms = appServices.get(savedURL);
		Integer CTR = new Integer(parms.get("ctr"));
		CTR++;
		parms.put("ctr", CTR.toString());

		String script = appServices.get(savedURL).get("welcome");
		if (script != null ) savedURL += script;
		return savedURL;		
	}
}

loadbalancer/src/main/java/com/assoc/jad/loadbalancer/DownloadServlet.java
package com.assoc.jad.loadbalancer;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;

import javax.faces.event.AbortProcessingException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet(urlPatterns = "/download/*", loadOnStartup = 1, asyncSupported = true)
public class DownloadServlet extends javax.servlet.http.HttpServlet implements
		javax.servlet.Servlet {

	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		performTask(request, response);
		while (System.getProperties().keySet().iterator().hasNext()) {
			String key = (String) System.getProperties().keySet().iterator().next();
			if (System.getProperty(key).startsWith("webapp")) System.out.println(key);
		}
	}

	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		performTask(request, response);
	}

	private void displayDoc(HttpServletResponse response, String document)
			throws IOException {

		int ndx = document.lastIndexOf('.');
		if (ndx == -1)
			throw new AbortProcessingException(
					"filename does not have an extension name=" + document);

		String type = document.substring(++ndx);

		File pdfFile = new File(document);

		response.setContentType("application/" + type);
		response.addHeader("Content-Disposition", "inline; filename="
				+ document + ";");
		response.setContentLength((int) pdfFile.length());

		FileInputStream fileInputStream = new FileInputStream(pdfFile);
		OutputStream responseOutputStream = response.getOutputStream();
		int bytes;
		while ((bytes = fileInputStream.read()) != -1) {
			responseOutputStream.write(bytes);
		}
		fileInputStream.close();
	}

	public void run() throws IOException {
	}

	private void performTask(HttpServletRequest request,HttpServletResponse response) throws ServletException, IOException {
		String document = request.getParameter("file");
		if (document != null) {
			displayDoc(response, document);
			return;
		}	}
}

loadbalancer/src/main/webapp/ApplicationInstances.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core" 
 	  xmlns:c="http://java.sun.com/jsp/jstl/core"
     xmlns:ui="http://java.sun.com/jsf/facelets" >
<head> 
		<link rel="stylesheet" href="includes/css/scrollNav.css" type="text/css"></link>
		<link href="includes/css/frames.css" type="text/css" rel="stylesheet"></link>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script type="text/javascript" src="includes/js/ajax.js"></script>
		<script type="text/javascript" src="includes/js/welcomePage.js"></script>
</head>  
	<body onload="fadeIn();bldMenu('ulmenu','#{healthCheckBean.applications}')">
	<h:form id="healthCheck" styleClass="menuCol noborder">
		<ui:include src="mainNavigation.xhtml" />
		<div id="contentframe" class="center">
		<h3>performance data for application #{healthCheckBean.selectedApp}</h3>
		<h4 id="infoMessage" style="">#{healthCheckBean.infomsg}</h4>
		
		<h:panelGrid columns="2" cellpadding="1" >		
			<h:outputLabel for="application" value="Application" />
			<h:selectOneMenu value="#{healthCheckBean.selectedApp}" id="application" immediate="true" onchange="this.form.submit()">
				<f:selectItem itemLabel="Select an application" itemValue="" />
				<f:selectItems value="#{healthCheckBean.applicationList}" /> 
			</h:selectOneMenu>
		</h:panelGrid>
		<br/><h3>General Server Data</h3>
			<c:forEach items="#{healthCheckBean.performanceService}" var="entry">
			<tr>
			<td><h:outputText value="#{entry.key}"/></td>
			  <c:forEach end="0" items="#{entry.value}" var="nestedentry1">   //display only one element from hash map
				<td><h:outputText value="#{nestedentry1.key}" /></td>
				  <table border="2" name="perfData">
					<c:forEach items="#{nestedentry1.value}" var="nestedentry2">
					  <tr>
						<c:set var="key" value="#{nestedentry2.key}"/>
						<c:if test="${key == 'schema' || key == 'instance' || key == 'serverName' || key == 'totalSwapSpaceSize' || key == 'instancePort' || key == 'loadBalancerWSURL' ||key == 'totalPhysicalMemorySize' || key == 'viewId'}">
						  <th><h:outputText value="#{nestedentry2.key}" /></th>
						  <td><h:outputText value="#{nestedentry2.value.get(0)}"/></td>    
						</c:if>
					  </tr>
					</c:forEach>
				  </table>
			  </c:forEach>
			</tr>
			</c:forEach>
			<c:forEach items="#{healthCheckBean.performanceService}" var="entry">

			<br/><h3>Performance Data </h3>
			  <c:forEach items="#{entry.value}" var="nestedentry1">
			  #{nestedentry1.key}
			  <table border="2" name="perfData">
				<tr><th>name</th><th>average</th><th>minimum</th><th>maximum</th></tr>
				<c:forEach items="#{nestedentry1.value}" var="nestedentry2">
					<c:set var="key" value="#{nestedentry2.key}"/>
					<c:set var="total" value="${0}"/>
					<c:set var="counter" value="${0}"/>
					<c:set var="min" value="${0}"/>
					<c:set var="max" value="${0}"/>
					<c:set var="flag" value="${0}"/>

					<c:if test="${key == 'freePhysicalMemorySize' || key == 'processTime' || key == 'freeSwapSpaceSize' || key == 'committedVirtualMemorySize' || key == 'processCpuLoad' || 
						key == 'systemCpuLoad' || key == 'processCpuTime' || key == 'networkBgnTime' || key == 'networkEndTime'}">
					  <tr><th><h:outputText value="#{nestedentry2.key}" /></th>
					  <c:forEach items="#{nestedentry2.value}" var="listValues">
						<c:set var="total" value="${total + listValues}" />
						<c:set var="counter" value="${counter + 1}" />
						<c:if test="${flag == 0}" >
						  <c:set var="min" value="${listValues}"/>
						  <c:set var="max" value="${listValues}"/>
						  <c:set var="flag" value="${1}"/>
						</c:if>
						<c:if test="${min - listValues gt 0.0}" >
						  <c:set var="min" value="${listValues}"/>
						</c:if>
						<c:if test="${max - listValues lt 0.0}" >
						  <c:set var="max" value="${listValues}"/>
						</c:if>
					  </c:forEach>
					  <td>${total/counter}</td><td>${min}</td><td>${max}</td>
					  </tr>
					</c:if>
				</c:forEach>
			  </table>
			  </c:forEach>
			</c:forEach>
		</div>
  		<input type="hidden" value="healthCheck" id="formname" name="formname"/>
</h:form>
  </body>
</html>

loadbalancer/src/main/webapp/graphBarDetail.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:f="http://java.sun.com/jsf/core" 
	  xmlns:h="http://java.sun.com/jsf/html" 
	  xmlns:ui="http://java.sun.com/jsf/facelets" 
	  xmlns:p="http://primefaces.org/ui"
	  xmlns="http://www.w3.org/1999/xhtml">
	  
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="text/javascript" src="includes/js/welcomePage.js"></script>
	<title>bar graph</title>
	<style type="text/css">
	    .right div {
	        float: right;
	    }
	</style>
</h:head> 
<body>
	<h:form id="barGraph">
	<div id="contentframe" class="multiselect center"> 
    <p:growl id="growl" showDetail="true" />
	<p:chart type="bar" model="#{barGraphBean.barModelDetail}" style="height:300px">
		<p:ajax event="itemSelect" listener="#{barGraphBean.itemSelectFromDetail}" update="growl" />
	</p:chart>
	</div>
	</h:form>
</body>
</html>

loadbalancer/src/main/webapp/graphBarRoot.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:f="http://java.sun.com/jsf/core" 
	  xmlns:h="http://java.sun.com/jsf/html" 
	  xmlns:ui="http://java.sun.com/jsf/facelets" 
	  xmlns:p="http://primefaces.org/ui"
	  xmlns="http://www.w3.org/1999/xhtml">
	  
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="text/javascript" src="includes/js/welcomePage.js"></script>
	<title>bar graph</title>
	<style type="text/css">
	    .right div {
	        float: right;
	    }
	</style>
</h:head> 
<body>
  <h:form id="barGraph">
  <div id="contentframe" class="multiselect center"> 
	<h:selectOneMenu value="#{barGraphBean.selectedField}" id="fields" immediate="true" onchange="this.form.submit()">
		<f:selectItem itemLabel="Select a field" itemValue="" />
		<f:selectItems value="#{barGraphBean.fieldList}" /> 
	</h:selectOneMenu>
    <p:growl id="growl" showDetail="true" />
	<p:chart type="bar" model="#{barGraphBean.barModelRoot}" style="height:300px">
		<p:ajax event="itemSelect" listener="#{barGraphBean.itemSelectFromRoot}" update="growl" />
	</p:chart>
  </div>
  </h:form>
</body>
</html>

loadbalancer/src/main/webapp/healthCheck.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core" 
	  xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets" >
<h:head> 
		<link rel="stylesheet" href="includes/css/scrollNav.css" type="text/css"></link>
		<link href="includes/css/frames.css" type="text/css" rel="stylesheet"></link>
		<link href="includes/css/modal.css" type="text/css" rel="stylesheet"></link>
		<script type="text/javascript" src="includes/js/ajax.js"></script>
		<script type="text/javascript" src="includes/js/welcomePage.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</h:head>  
<body onload="fadeIn();bldMenu('ulmenu','#{healthCheckBean.applications}');onloadGraph('myModal')">
  <h:form id="healthCheck" styleClass="menuCol noborder">
		<ui:include src="mainNavigation.xhtml" />
		<div id="contentframe" class="center">
		<h2>display instances availability by application</h2>

		<h4 id="infoMessage" style="">#{healthCheckBean.infomsg}</h4>
		<h:selectOneMenu value="#{healthCheckBean.selectedApp}" id="application" immediate="true" onchange="this.form.submit()">
			<f:selectItem itemLabel="Select an application" itemValue="" />
			<f:selectItems value="#{healthCheckBean.applicationList}" /> 
		</h:selectOneMenu>
		<h:dataTable id="tblInstances" border="2" value="#{healthCheckBean.applicationService}" var="appKey" >
			<h:column>
				<f:facet name = "header">Data</f:facet>  
				<a href="javascript:instanceData('#{appKey}')" style="color:black;">Display Data</a>
			</h:column>
			<h:column>
				<f:facet name = "header">Graph</f:facet>  
				<a href="javascript:instanceDataGraph('#{appKey}')" style="color:black;">Graph Data</a>
			</h:column>
			<h:column>
				<f:facet name = "header">URL</f:facet>  
				<h:outputText value="#{appKey}" />
			</h:column>
			<h:column>
					<f:facet name = "header">record</f:facet>  
				<h:dataTable value="#{healthCheckBean.service2}" var="serv">
					<h:column>
					<h:outputText  value="#{serv.get(appKey)}" />
					</h:column>
				</h:dataTable>
			</h:column>
		</h:dataTable>		
		</div>
  		<input type="hidden" value="healthCheck" id="formname" name="formname"/>
  </h:form>
</body>
</html>

loadbalancer/src/main/webapp/test.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
<link rel="stylesheet" href="includes/css/scrollNav.css" type="text/css"></link>
<link rel="stylesheet" href="includes/css/style.css" type="text/css"></link>
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript" src="includes/js/shoplist.js"></script>
<script type="text/javascript" src="includes/js/shoplistSupport.js"></script>
<script type="text/javascript" src="includes/js/ajax.js"></script>
</head>
<body onload="showNav('mainNavigation.xhtml')">
<h:form id="healthCheck" styleClass="menuCol noborder">
	<div id="contentframe" class="center">
		<h2>To add a new shopping Item to Stores</h2>

		<h4 id="infoMessage" style="">#{healthCheckBean.infomsg}</h4>
		<h:selectOneMenu value="#{healthCheckBean.selectedApp}" id="application" immediate="true" onchange="this.form.submit()">
			<f:selectItem itemLabel="Select an application" itemValue="" />
			<f:selectItems value="#{healthCheckBean.applicationList}" /> 
		</h:selectOneMenu>
			<h:dataTable border="2" value="#{healthCheckBean.applicationService}" var="appKey" >
				<h:column><h:outputText value="#{appKey}" />
				</h:column>
				<h:column>
					<h:dataTable value="#{healthCheckBean.service2}" var="serv">
						<h:column>
						<f:facet name = "header">#{serv.key.get('instance')}</f:facet>  
						<h:outputText  value="#{serv.get(appKey)}" />
						</h:column>
					</h:dataTable>
				</h:column>
			</h:dataTable>		
		<h:dataTable border="2" value="#{healthCheckBean.service}" var="serv">
			<h:column>
			<f:facet name = "header">#{serv.key.get('instance')}</f:facet>  
			<h:outputText  value="#{serv}" />
			</h:column>
		</h:dataTable>

	</div>
</h:form>
</body>
</html>